feat: add new node label supported by k8s version 1.17 (#18)
* feat: add new node label supported by k8s version 1.17

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -9,7 +9,7 @@ jobs:
     machine:
       image: ubuntu-1604:202004-01
     environment:
-      GOLANG_VERSION: 1.14.2
+      GOLANG_VERSION: 1.14.4
       # https://github.com/operator-framework/operator-sdk/releases
       OPERATOR_SDK_VERSION: v0.17.1
       # https://github.com/github/hub/releases
@@ -80,8 +80,8 @@ jobs:
       # https://github.com/kubernetes-sigs/kind/releases
       KIND_VERSION: v0.8.1
       # https://github.com/helm/helm/releases
-      HELM_VERSION: v3.2.1
-      GOLANG_VERSION: 1.14.2
+      HELM_VERSION: v3.2.4
+      GOLANG_VERSION: 1.14.4
       # https://github.com/operator-framework/operator-sdk/releases
       OPERATOR_SDK_VERSION: v0.17.1
 
@@ -133,18 +133,20 @@ jobs:
       - run:
           name: start kind
           command: |
-            kind create cluster --quiet --name operator
+            kind create cluster --quiet --name operator --config .circleci/kind-operator-config.yaml
             JSONPATH='{range .items[*]}{@.metadata.name}:{range @.status.conditions[*]}{@.type}={@.status};{end}{end}';
             until kubectl get nodes -o jsonpath="$JSONPATH" 2>&1 | grep -q "Ready=True"; do
               sleep 1;
             done
 
-            kubectl label nodes operator-control-plane beta.kubernetes.io/instance-type=m5a.2xlarge
+            kubectl label nodes operator-control-plane node.kubernetes.io/instance-type=m5a.2xlarge
+            kubectl label nodes operator-worker beta.kubernetes.io/instance-type=m5a.2xlarge
 
             # Dump cluster info
             kubectl cluster-info
             kubectl version
             kubectl describe node operator-control-plane
+            kubectl describe node operator-worker
       - run:
           name: install helm
           command: |
@@ -171,8 +173,16 @@ jobs:
           name: Run Local Tests
           command: |
             nohup make run/local &
-            sleep 75
+            sleep 150
             RESULT=$( kubectl get node operator-control-plane -o json | jq -r '.status.capacity["eksattachments"]' )
+            if [[ $RESULT != "23" ]]; then
+              echo "Pipeline failed"
+              exit 1
+            else
+              echo "Success"
+            fi
+            sleep 10
+            RESULT=$( kubectl get node operator-worker -o json | jq -r '.status.capacity["eksattachments"]' )
             if [[ $RESULT != "23" ]]; then
               echo "Pipeline failed"
               exit 1
